export const ROUTE_CHANGE = 'ROUTE_CHANGE'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const  LOAD_ALL_CLIENTS_SUCCESS = 'LOAD_ALL_CLIENTS_SUCCESS'
export const  LOAD_ALL_CLIENTS_FAILED = 'LOAD_ALL_CLIENTS_FAILED'
export const  LOAD_CLIENT_SUCCESS = 'LOAD_CLIENT_SUCCESS'

export const  LOAD_ALL_PRODUCTS_SUCCESS = 'LOAD_ALL_PRODUCTS_SUCCESS'
export const  LOAD_ALL_PRODUCTS_FAILED = 'LOAD_ALL_PRODUCTS_FAILED'
export const  LOAD_PRODUCT_SUCCESS = 'LOAD_PRODUCT_SUCCESS'
