export const ROUTE_CHANGE = 'ROUTE_CHANGE'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const  LOAD_VEHICLE_CATEGORY_SUCCESS = 'LOAD_VEHICLE_CATEGORY_SUCCESS'
export const  LOAD_VEHICLE_CATEGORY_FAILED = 'LOAD_VEHICLE_CATEGORY_FAILED'