export const ROUTE_CHANGE = 'ROUTE_CHANGE'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const  LOAD_ALL_VEHICLE_CATEGORY_SUCCESS = 'LOAD_ALL_VEHICLE_CATEGORY_SUCCESS'
export const  LOAD_ALL_VEHICLE_CATEGORY_FAILED = 'LOAD_ALL_VEHICLE_CATEGORY_FAILED'
export const LOAD_VEHICLE_CATEGORY_SUCCESS = 'LOAD_VEHICLE_CATEGORY_SUCCESS'

export const  LOAD_ALL_CLIENTS_SUCCESS = 'LOAD_ALL_CLIENTS_SUCCESS'
export const  LOAD_ALL_CLIENTS_FAILED = 'LOAD_ALL_CLIENTS_FAILED'
export const  LOAD_CLIENT_SUCCESS = 'LOAD_CLIENT_SUCCESS'
